version: "1.0"
stages:
  - "lint"

steps:
 lint:
   title: "YAML Lint"
   description: "Validate YAML syntax"
   # type: "github-action-executor"
   type: "freestyle"
   image: "codefresh/github-action-converter:latest"
   stage: "lint"
   environment:
     - INPUT_FILE_OR_DIR="/"
     - INPUT_CONFIG_FILE="/tmp/.yamllint.yaml"
     - INPUT_FORMAT="colored"
   # arguments:
     # url: 'https://github.com/marketplace/actions/yaml-lint'
     # envs:
     # INPUT_FILE_OR_DIR: "/"
     # INPUT_CONFIG_FILE: "/tmp/.yamllint.yaml"
     # INPUT_FORMAT: "colored"
     # registry: "dockerhub"
     # registry_repo: "codefreshplugins"