# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "lint"

steps:
 lint:
   title: "YAML Lint"
   description: "Validate YAML syntax"
   type: "github-action-executor"
   arguments:
     url: 'https://github.com/marketplace/actions/yaml-lint'
     envs:
       - INPUT_FILE_OR_DIR: "/"
       # - INPUT_FILE_OR_DIR: "./**/*val*.yaml"
       # - INPUT_CONFIG_FILE: "./.yamllint.yaml"
       - INPUT_FORMAT: "colored"
     registry: "dockerhub"
     registry_repo: "codefreshplugins"
