version: "1.0"
stages:
  - "lint"

steps:
 lint:
   title: "YAML Lint"
   description: "Validate YAML syntax"
   type: "github-action-executor"
   arguments:
     url: 'https://github.com/marketplace/actions/yaml-lint'
     envs:
       - INPUT_FILE_OR_DIR: "/"
       - INPUT_CONFIG_FILE: "/.yamllint.yaml"
       - INPUT_FORMAT: "colored"
     registry: "dockerhub"
     registry_repo: "codefreshplugins"